/**
 * app/api/curriculum/[id]/regenerate-module/route.ts
 * ─────────────────────────────────────────────────────────────
 * POST /api/curriculum/:id/regenerate-module
 *
 * Rewrites the content of a single module in-place.  The module's
 * structure (id, title, lesson stubs) is preserved, but the keyPoints,
 * content, suggestedResources, and quiz are all regenerated by Claude.
 *
 * Body:    { module_id: string, instructions?: string }
 * Returns: { success: true, module: Module }
 * Auth:    Required. Must own the course. Course must be in "ready" state.
 *
 * Design notes:
 *   • We do NOT queue this as a background job. A single module takes
 *     ~30–90s which fits comfortably inside the Vercel function budget.
 *   • The caller can optionally pass `instructions` — free-form text
 *     that is appended to the prompt, e.g. "make it more hands-on" or
 *     "focus on clinical examples". This is what unlocks the "edit my
 *     course" experience without full regeneration.
 * ─────────────────────────────────────────────────────────────
 */

import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import {
  buildModuleDetailCurriculumPrompt,
} from "@/lib/prompts/curriculum";
import { callClaudeEdit, extractText, parseClaudeJson } from "@/lib/claude/edit";
import { loadCourseForEdit } from "@/lib/curriculum/loadForEdit";
import type {
  GenerateRequest,
  Module,
  Lesson,
  QuizQuestion,
  AudienceLevel,
  CourseLength,
  TeachingStyle,
  OutputStructure,
  CourseLanguage,
} from "@/types/curriculum";

export const dynamic = "force-dynamic";

/** This route can take ~90s for a complex module, so extend the function budget. */
export const maxDuration = 300;

interface ModuleDetailPayload {
  lessons: Array<Partial<Lesson> & { id: string; title: string }>;
  quiz?: QuizQuestion[];
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: courseId } = await params;
    const body = await req.json().catch(() => ({}));
    const moduleId: unknown = body?.module_id;
    const userInstructions: string | null =
      typeof body?.instructions === "string" && body.instructions.trim().length > 0
        ? body.instructions.trim().slice(0, 500)
        : null;

    if (typeof moduleId !== "string" || moduleId.length === 0) {
      return NextResponse.json(
        { error: "module_id is required." },
        { status: 400 }
      );
    }

    const loaded = await loadCourseForEdit(courseId);
    if (loaded.kind === "error") {
      return NextResponse.json({ error: loaded.error }, { status: loaded.status });
    }

    const curriculum = loaded.course.curriculum!;
    const moduleIndex = curriculum.modules.findIndex((m) => m.id === moduleId);
    if (moduleIndex === -1) {
      return NextResponse.json(
        { error: "Module not found in this course." },
        { status: 404 }
      );
    }
    const currentModule = curriculum.modules[moduleIndex];

    // Rebuild a GenerateRequest-shaped object from the stored course so we
    // can feed it to the same prompt builder used during initial creation.
    // This keeps the regenerated output stylistically consistent with the
    // rest of the course (same teaching style, audience, language, etc.).
    const regenRequest: GenerateRequest = {
      topic: loaded.course.topic,
      audience: (loaded.course.audience || "intermediate") as AudienceLevel,
      length: (loaded.course.length || "short") as CourseLength,
      niche: loaded.course.niche ?? undefined,
      language: (loaded.course.language || "en") as CourseLanguage,
      includeQuizzes: loaded.course.include_quizzes ?? true,
      teachingStyle: (loaded.course.teaching_style || "conversational") as TeachingStyle,
      outputStructure: (loaded.course.output_structure || "modules") as OutputStructure,
      learnerProfile: loaded.course.learner_profile ?? undefined,
      abstract: loaded.course.course_abstract ?? undefined,
    };

    // Build the standard module-detail prompt, then optionally append
    // user instructions as an extra paragraph at the end.
    const { system, messages } = buildModuleDetailCurriculumPrompt(
      regenRequest,
      curriculum.title,
      curriculum.description,
      {
        id: currentModule.id,
        title: currentModule.title,
        description: currentModule.description,
        objectives: currentModule.objectives,
        lessons: currentModule.lessons.map((l) => ({
          id: l.id,
          title: l.title,
          description: l.description,
          format: l.format,
          durationMinutes: l.durationMinutes,
          objectives: l.objectives,
          order: l.order,
        })),
      },
      moduleIndex,
      curriculum.modules.length,
    );

    const augmentedMessages: Anthropic.MessageParam[] = messages.map((m) => ({
      role: m.role,
      content:
        userInstructions && m.role === "user"
          ? `${m.content}\n\nADDITIONAL USER DIRECTION (highest priority — override conflicting defaults):\n${userInstructions}`
          : m.content,
    }));

    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    const response = await callClaudeEdit({
      anthropic,
      system,
      messages: augmentedMessages,
      maxTokens: 16_384,
      label: `regen-module/${courseId}/${moduleId}`,
      timeoutMs: 140_000,
    });

    const rawText = extractText(response);
    const detail = parseClaudeJson<ModuleDetailPayload>(
      rawText,
      `regen-module/${moduleId}`
    );

    if (!detail?.lessons || !Array.isArray(detail.lessons)) {
      return NextResponse.json(
        { error: "Model did not return the expected module structure." },
        { status: 502 }
      );
    }

    // Merge the new content into the existing lessons by matching ids.
    // This preserves ordering and any fields Claude may have omitted.
    const mergedLessons: Lesson[] = currentModule.lessons.map((lesson) => {
      const next = detail.lessons.find((l) => l.id === lesson.id);
      if (!next) return lesson;
      return {
        ...lesson,
        keyPoints: next.keyPoints ?? lesson.keyPoints,
        content: next.content ?? lesson.content,
        suggestedResources: next.suggestedResources ?? lesson.suggestedResources,
      };
    });

    const updatedModule: Module = {
      ...currentModule,
      lessons: mergedLessons,
      quiz: detail.quiz && detail.quiz.length > 0 ? detail.quiz : currentModule.quiz,
    };

    // Persist the updated curriculum JSON back to Supabase.
    const nextCurriculum = {
      ...curriculum,
      modules: curriculum.modules.map((m, i) => (i === moduleIndex ? updatedModule : m)),
      updatedAt: new Date().toISOString(),
    };

    const { error } = await loaded.admin
      .from("courses")
      .update({
        curriculum: JSON.parse(JSON.stringify(nextCurriculum)),
        updated_at: new Date().toISOString(),
      })
      .eq("id", courseId);

    if (error) {
      console.error("[/api/curriculum/:id/regenerate-module] update error:", error);
      return NextResponse.json(
        { error: "Could not save regenerated module." },
        { status: 500 }
      );
    }

    return NextResponse.json(
      { success: true, module: updatedModule },
      { status: 200 }
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[/api/curriculum/:id/regenerate-module] unexpected error:", msg);
    return NextResponse.json(
      { error: "Unexpected error.", details: msg },
      { status: 500 }
    );
  }
}
