import {
  Document,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  VerticalAlign,
  UnderlineType,
  PageBreak,
  Packer,
  convertInchesToTwip,
  ShadingType,
  Footer,
} from "docx";
import { Curriculum, Module, Lesson, QuizQuestion } from "@/types/curriculum";

// Brand Colors
const COLORS = {
  primary: "6D28D9", // Violet
  light: "8B5CF6", // Light Violet
  dark: "4C1D95", // Dark Violet
  text: "1F2937", // Dark Gray
  lightGray: "F3F4F6", // Light Gray
  border: "E5E7EB", // Border Gray
};

const FOOTER_TEXT = "Generated by Syllabi";

/**
 * Generate a premium Word document from a Curriculum object
 */
export async function generateCurriculumDocx(
  curriculum: Curriculum
): Promise<Blob> {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          ...createCoverPage(curriculum),
          new Paragraph({ text: "", pageBreakBefore: true }),
          ...createTableOfContents(curriculum),
          new Paragraph({ text: "", pageBreakBefore: true }),
          ...createCourseOverview(curriculum),
          new Paragraph({ text: "", pageBreakBefore: true }),
          ...createModuleSections(curriculum),
          new Paragraph({ text: "", pageBreakBefore: true }),
          ...createPacingSchedule(curriculum),
          new Paragraph({ text: "", pageBreakBefore: true }),
          ...createBonusResources(curriculum),
          new Paragraph({ text: "", pageBreakBefore: true }),
          ...createLearningChecklist(curriculum),
        ],
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                text: FOOTER_TEXT,
                alignment: AlignmentType.CENTER,
                style: "footer",
                children: [
                  new TextRun({
                    text: FOOTER_TEXT,
                    size: 18,
                    color: COLORS.primary,
                    italics: true,
                  }),
                ],
              }),
            ],
          }),
        },
      },
    ],
  });

  return await Packer.toBlob(doc);
}

/**
 * Create the cover page with title, subtitle, and stats
 */
function createCoverPage(curriculum: Curriculum): Paragraph[] {
  const totalLessons = curriculum.modules.reduce(
    (sum, m) => sum + m.lessons.length,
    0
  );
  const totalHours = Math.round(curriculum.pacing.totalHours * 10) / 10;

  return [
    // Spacer
    new Paragraph({ text: "" }),
    new Paragraph({ text: "" }),
    new Paragraph({ text: "" }),

    // Title
    new Paragraph({
      text: curriculum.title,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: curriculum.title,
          size: 72,
          bold: true,
          color: COLORS.primary,
          font: "Calibri",
        }),
      ],
    }),

    // Subtitle
    new Paragraph({
      text: curriculum.subtitle,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: curriculum.subtitle,
          size: 28,
          color: COLORS.light,
          italics: true,
        }),
      ],
    }),

    // Stats Grid
    new Paragraph({
      text: "",
      spacing: { before: 300, after: 300 },
    }),

    createStatBox("Modules", curriculum.modules.length.toString()),
    new Paragraph({ text: "" }),
    createStatBox("Lessons", totalLessons.toString()),
    new Paragraph({ text: "" }),
    createStatBox("Hours", totalHours.toString()),
    new Paragraph({ text: "" }),
    createStatBox("Level", curriculum.difficulty.charAt(0).toUpperCase() + curriculum.difficulty.slice(1)),

    // Spacer
    new Paragraph({ text: "", spacing: { before: 400 } }),

    // Description
    new Paragraph({
      text: curriculum.description,
      alignment: AlignmentType.CENTER,
      spacing: { before: 200, after: 200, line: 360 },
      children: [
        new TextRun({
          text: curriculum.description,
          size: 22,
          color: COLORS.text,
        }),
      ],
    }),

    // Target Audience
    new Paragraph({
      text: "",
      spacing: { before: 300 },
    }),
    new Paragraph({
      text: "Target Audience",
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: "Target Audience",
          size: 20,
          bold: true,
          color: COLORS.primary,
        }),
      ],
    }),
    new Paragraph({
      text: curriculum.targetAudience,
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: curriculum.targetAudience,
          size: 22,
          color: COLORS.text,
        }),
      ],
    }),
  ];
}

/**
 * Create a stat box in the cover page
 */
function createStatBox(label: string, value: string): Paragraph {
  return new Paragraph({
    text: `${label}: ${value}`,
    alignment: AlignmentType.CENTER,
    spacing: { line: 240 },
    children: [
      new TextRun({
        text: `${label}: `,
        size: 24,
        bold: true,
        color: COLORS.dark,
      }),
      new TextRun({
        text: value,
        size: 28,
        bold: true,
        color: COLORS.primary,
      }),
    ],
  });
}

/**
 * Create the Table of Contents section
 */
function createTableOfContents(curriculum: Curriculum): Paragraph[] {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: "Table of Contents",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: "Table of Contents",
          size: 32,
          bold: true,
          color: COLORS.primary,
        }),
      ],
    }),
  ];

  // Add module entries
  curriculum.modules.forEach((module, idx) => {
    paragraphs.push(
      new Paragraph({
        text: `${idx + 1}. ${module.title}`,
        spacing: { after: 120, before: 80 },
        children: [
          new TextRun({
            text: `${idx + 1}. ${module.title}`,
            size: 22,
            bold: true,
            color: COLORS.text,
          }),
        ],
      })
    );

    // Add lesson entries
    module.lessons.forEach((lesson) => {
      paragraphs.push(
        new Paragraph({
          text: `  • ${lesson.title}`,
          spacing: { after: 60 },
          children: [
            new TextRun({
              text: `  • ${lesson.title}`,
              size: 20,
              color: COLORS.text,
            }),
          ],
        })
      );
    });
  });

  return paragraphs;
}

/**
 * Create the Course Overview section
 */
function createCourseOverview(curriculum: Curriculum): Paragraph[] {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: "Course Overview",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: "Course Overview",
          size: 32,
          bold: true,
          color: COLORS.primary,
        }),
      ],
    }),

    // Learning Objectives
    new Paragraph({
      text: "Learning Objectives",
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 200 },
      children: [
        new TextRun({
          text: "Learning Objectives",
          size: 26,
          bold: true,
          color: COLORS.light,
        }),
      ],
    }),
  ];

  // Add objectives as numbered list
  curriculum.objectives.forEach((obj, idx) => {
    paragraphs.push(
      new Paragraph({
        text: obj,
        spacing: { after: 100 },
        children: [
          new TextRun({
            text: `${idx + 1}. `,
            bold: true,
            color: COLORS.primary,
            size: 22,
          }),
          new TextRun({
            text: obj,
            size: 22,
            color: COLORS.text,
          }),
        ],
      })
    );
  });

  // Prerequisites
  if (curriculum.prerequisites && curriculum.prerequisites.length > 0) {
    paragraphs.push(
      new Paragraph({
        text: "",
        spacing: { before: 200 },
      }),
      new Paragraph({
        text: "Prerequisites",
        heading: HeadingLevel.HEADING_2,
        spacing: { after: 200 },
        children: [
          new TextRun({
            text: "Prerequisites",
            size: 26,
            bold: true,
            color: COLORS.light,
          }),
        ],
      })
    );

    curriculum.prerequisites.forEach((prereq) => {
      paragraphs.push(
        new Paragraph({
          text: prereq,
          spacing: { after: 80 },
          children: [
            new TextRun({
              text: "• ",
              bold: true,
              color: COLORS.primary,
            }),
            new TextRun({
              text: prereq,
              size: 22,
            }),
          ],
        })
      );
    });
  }

  // Pacing Information
  paragraphs.push(
    new Paragraph({
      text: "",
      spacing: { before: 200 },
    }),
    new Paragraph({
      text: "Pacing Information",
      heading: HeadingLevel.HEADING_2,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: "Pacing Information",
          size: 26,
          bold: true,
          color: COLORS.light,
        }),
      ],
    }),
    new Paragraph({
      text: `Style: ${curriculum.pacing.style.charAt(0).toUpperCase() + curriculum.pacing.style.slice(1).replace("-", " ")}`,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: "Style: ",
          bold: true,
          color: COLORS.primary,
        }),
        new TextRun({
          text: curriculum.pacing.style
            .charAt(0)
            .toUpperCase() + curriculum.pacing.style.slice(1).replace("-", " "),
        }),
      ],
    }),
    new Paragraph({
      text: `Total Hours: ${curriculum.pacing.totalHours}`,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: "Total Hours: ",
          bold: true,
          color: COLORS.primary,
        }),
        new TextRun({
          text: curriculum.pacing.totalHours.toString(),
        }),
      ],
    }),
    new Paragraph({
      text: `Hours Per Week: ${curriculum.pacing.hoursPerWeek}`,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: "Hours Per Week: ",
          bold: true,
          color: COLORS.primary,
        }),
        new TextRun({
          text: curriculum.pacing.hoursPerWeek.toString(),
        }),
      ],
    }),
    new Paragraph({
      text: `Total Weeks: ${curriculum.pacing.totalWeeks}`,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: "Total Weeks: ",
          bold: true,
          color: COLORS.primary,
        }),
        new TextRun({
          text: curriculum.pacing.totalWeeks.toString(),
        }),
      ],
    })
  );

  return paragraphs;
}

/**
 * Create individual module sections with lessons and quizzes
 */
function createModuleSections(curriculum: Curriculum): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  curriculum.modules.forEach((module, moduleIdx) => {
    // Module heading
    paragraphs.push(
      new Paragraph({
        text: `Module ${moduleIdx + 1}: ${module.title}`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        children: [
          new TextRun({
            text: `Module ${moduleIdx + 1}: ${module.title}`,
            size: 32,
            bold: true,
            color: COLORS.primary,
          }),
        ],
      }),
      new Paragraph({
        text: module.description,
        spacing: { after: 300 },
        children: [
          new TextRun({
            text: module.description,
            size: 22,
            color: COLORS.text,
          }),
        ],
      })
    );

    // Module objectives
    if (module.objectives && module.objectives.length > 0) {
      paragraphs.push(
        new Paragraph({
          text: "Module Objectives",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 200 },
          children: [
            new TextRun({
              text: "Module Objectives",
              size: 26,
              bold: true,
              color: COLORS.light,
            }),
          ],
        })
      );

      module.objectives.forEach((obj, idx) => {
        paragraphs.push(
          new Paragraph({
            text: obj,
            spacing: { after: 100 },
            children: [
              new TextRun({
                text: `${idx + 1}. `,
                bold: true,
                color: COLORS.primary,
              }),
              new TextRun({
                text: obj,
                size: 20,
              }),
            ],
          })
        );
      });

      paragraphs.push(
        new Paragraph({
          text: "",
          spacing: { after: 200 },
        })
      );
    }

    // Lessons
    module.lessons.forEach((lesson, lessonIdx) => {
      paragraphs.push(...createLessonContent(lesson, lessonIdx, moduleIdx));
    });

    // Module quiz
    if (module.quiz && module.quiz.length > 0) {
      paragraphs.push(
        new Paragraph({
          text: "",
          spacing: { before: 300 },
        }),
        new Paragraph({
          text: "Module Quiz",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 200 },
          children: [
            new TextRun({
              text: "Module Quiz",
              size: 26,
              bold: true,
              color: COLORS.light,
            }),
          ],
        })
      );

      module.quiz.forEach((question, qIdx) => {
        paragraphs.push(...createQuestionContent(question, qIdx));
      });
    }

    paragraphs.push(
      new Paragraph({
        text: "",
        spacing: { before: 300, after: 300 },
      })
    );
  });

  return paragraphs;
}

/**
 * Strip basic markdown formatting from text and return plain text
 */
function stripMarkdown(markdown: string): string {
  return markdown
    .replace(/\*\*(.*?)\*\*/g, "$1") // Bold
    .replace(/\*(.*?)\*/g, "$1") // Italic
    .replace(/__(.*?)__/g, "$1") // Bold alternative
    .replace(/_(.*?)_/g, "$1") // Italic alternative
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1") // Links
    .replace(/^#+\s+/gm, "") // Headers
    .replace(/^-\s+/gm, "") // Unordered lists
    .replace(/^\d+\.\s+/gm, ""); // Ordered lists
}

/**
 * Split markdown content into paragraphs and return as Paragraph objects
 */
function createContentParagraphs(markdown: string | undefined): Paragraph[] {
  if (!markdown || !markdown.trim()) {
    return [];
  }

  // Split by double newlines to get paragraphs
  const paragraphTexts = markdown
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  return paragraphTexts.map(
    (text) =>
      new Paragraph({
        text: stripMarkdown(text),
        spacing: { after: 120 },
        children: [
          new TextRun({
            text: stripMarkdown(text),
            size: 18,
            color: COLORS.text,
          }),
        ],
      })
  );
}

/**
 * Create lesson content with title, format badge, duration, objectives, key points, and resources
 */
function createLessonContent(
  lesson: Lesson,
  lessonIdx: number,
  moduleIdx: number
): Paragraph[] {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: `Lesson ${lessonIdx + 1}: ${lesson.title}`,
      heading: HeadingLevel.HEADING_3,
      spacing: { before: 200, after: 150 },
      children: [
        new TextRun({
          text: `Lesson ${lessonIdx + 1}: ${lesson.title}`,
          size: 24,
          bold: true,
          color: COLORS.dark,
        }),
      ],
    }),

    // Format badge and duration
    new Paragraph({
      text: `Format: ${lesson.format} | Duration: ${lesson.durationMinutes} minutes`,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: `Format: `,
          bold: true,
          color: COLORS.primary,
          size: 20,
        }),
        new TextRun({
          text: formatBadge(lesson.format),
          size: 20,
          color: COLORS.light,
          bold: true,
        }),
        new TextRun({
          text: ` | Duration: `,
          bold: true,
          color: COLORS.primary,
          size: 20,
        }),
        new TextRun({
          text: `${lesson.durationMinutes} minutes`,
          size: 20,
        }),
      ],
    }),

    // Description
    new Paragraph({
      text: lesson.description,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: lesson.description,
          size: 20,
          color: COLORS.text,
        }),
      ],
    }),
  ];

  // Lesson content (rich markdown body text)
  if (lesson.content && lesson.content.trim()) {
    paragraphs.push(...createContentParagraphs(lesson.content));
    paragraphs.push(
      new Paragraph({
        text: "",
        spacing: { after: 150 },
      })
    );
  }

  // Lesson objectives
  if (lesson.objectives && lesson.objectives.length > 0) {
    paragraphs.push(
      new Paragraph({
        text: "Objectives",
        heading: HeadingLevel.HEADING_4,
        spacing: { after: 100 },
        children: [
          new TextRun({
            text: "Objectives",
            size: 22,
            bold: true,
            color: COLORS.light,
          }),
        ],
      })
    );

    lesson.objectives.forEach((obj) => {
      paragraphs.push(
        new Paragraph({
          text: obj,
          spacing: { after: 80 },
          children: [
            new TextRun({
              text: "• ",
              bold: true,
              color: COLORS.primary,
            }),
            new TextRun({
              text: obj,
              size: 20,
            }),
          ],
        })
      );
    });

    paragraphs.push(
      new Paragraph({
        text: "",
        spacing: { after: 150 },
      })
    );
  }

  // Key points
  if (lesson.keyPoints && lesson.keyPoints.length > 0) {
    paragraphs.push(
      new Paragraph({
        text: "Key Points",
        heading: HeadingLevel.HEADING_4,
        spacing: { after: 100 },
        children: [
          new TextRun({
            text: "Key Points",
            size: 22,
            bold: true,
            color: COLORS.light,
          }),
        ],
      })
    );

    lesson.keyPoints.forEach((point, idx) => {
      paragraphs.push(
        new Paragraph({
          text: point,
          spacing: { after: 80 },
          children: [
            new TextRun({
              text: `${idx + 1}. `,
              bold: true,
              color: COLORS.primary,
            }),
            new TextRun({
              text: point,
              size: 20,
            }),
          ],
        })
      );
    });

    paragraphs.push(
      new Paragraph({
        text: "",
        spacing: { after: 150 },
      })
    );
  }

  // Suggested resources
  if (lesson.suggestedResources && lesson.suggestedResources.length > 0) {
    paragraphs.push(
      new Paragraph({
        text: "Suggested Resources",
        heading: HeadingLevel.HEADING_4,
        spacing: { after: 100 },
        children: [
          new TextRun({
            text: "Suggested Resources",
            size: 22,
            bold: true,
            color: COLORS.light,
          }),
        ],
      })
    );

    lesson.suggestedResources.forEach((resource) => {
      paragraphs.push(
        new Paragraph({
          text: `${resource.title} (${resource.type})`,
          spacing: { after: 60 },
          children: [
            new TextRun({
              text: "• ",
              bold: true,
              color: COLORS.primary,
            }),
            new TextRun({
              text: resource.title,
              size: 20,
              bold: true,
            }),
            new TextRun({
              text: ` (${resource.type})`,
              size: 20,
              italics: true,
            }),
          ],
        }),
        new Paragraph({
          text: `${resource.url}`,
          spacing: { after: 80 },
          children: [
            new TextRun({
              text: `${resource.url}`,
              size: 18,
              color: "0066CC",
            }),
          ],
        })
      );
    });
  }

  // Lesson quiz
  if (lesson.quiz && lesson.quiz.length > 0) {
    paragraphs.push(
      new Paragraph({
        text: "",
        spacing: { before: 150, after: 100 },
      }),
      new Paragraph({
        text: "Lesson Quiz",
        heading: HeadingLevel.HEADING_4,
        spacing: { after: 150 },
        children: [
          new TextRun({
            text: "Lesson Quiz",
            size: 22,
            bold: true,
            color: COLORS.light,
          }),
        ],
      })
    );

    lesson.quiz.forEach((question, qIdx) => {
      paragraphs.push(...createQuestionContent(question, qIdx));
    });
  }

  return paragraphs;
}

/**
 * Create quiz question content
 */
function createQuestionContent(question: QuizQuestion, qIdx: number): Paragraph[] {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: `Question ${qIdx + 1}: ${question.question}`,
      spacing: { before: 100, after: 150 },
      children: [
        new TextRun({
          text: `Question ${qIdx + 1}: `,
          bold: true,
          color: COLORS.primary,
          size: 20,
        }),
        new TextRun({
          text: question.question,
          size: 20,
        }),
      ],
    }),
  ];

  // Options
  if (question.options && question.options.length > 0) {
    question.options.forEach((option, optIdx) => {
      const isCorrect =
        typeof question.correctAnswer === "number" &&
        question.correctAnswer === optIdx;

      paragraphs.push(
        new Paragraph({
          text: `${String.fromCharCode(65 + optIdx)}. ${option}`,
          spacing: { after: 80 },
          shading: isCorrect
            ? {
                type: ShadingType.CLEAR,
                color: "E0F2FE",
                fill: "E0F2FE",
              }
            : undefined,
          children: [
            new TextRun({
              text: `${String.fromCharCode(65 + optIdx)}. `,
              bold: true,
              color: isCorrect ? COLORS.primary : COLORS.text,
              size: 20,
            }),
            new TextRun({
              text: option,
              size: 20,
              bold: isCorrect,
              color: isCorrect ? COLORS.primary : COLORS.text,
            }),
            isCorrect
              ? new TextRun({
                  text: " ✓",
                  bold: true,
                  color: "10B981",
                  size: 20,
                })
              : new TextRun({
                  text: "",
                }),
          ],
        })
      );
    });
  }

  // Explanation
  if (question.explanation) {
    paragraphs.push(
      new Paragraph({
        text: "",
        spacing: { after: 100 },
      }),
      new Paragraph({
        text: `Explanation: ${question.explanation}`,
        spacing: { after: 200 },
        children: [
          new TextRun({
            text: "Explanation: ",
            bold: true,
            color: COLORS.primary,
            size: 20,
          }),
          new TextRun({
            text: question.explanation,
            size: 20,
            italics: true,
          }),
        ],
      })
    );
  }

  return paragraphs;
}

/**
 * Create the pacing schedule as a formatted table
 */
function createPacingSchedule(curriculum: Curriculum): (Paragraph | Table)[] {
  const paragraphs: (Paragraph | Table)[] = [
    new Paragraph({
      text: "Pacing Schedule",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: "Pacing Schedule",
          size: 32,
          bold: true,
          color: COLORS.primary,
        }),
      ],
    }),
  ];

  // Summary
  paragraphs.push(
    new Paragraph({
      text: `This ${curriculum.pacing.style} course is designed to be completed over ${curriculum.pacing.totalWeeks} weeks at ${curriculum.pacing.hoursPerWeek} hours per week, for a total of ${curriculum.pacing.totalHours} hours.`,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: `This ${curriculum.pacing.style} course is designed to be completed over ${curriculum.pacing.totalWeeks} weeks at ${curriculum.pacing.hoursPerWeek} hours per week, for a total of ${curriculum.pacing.totalHours} hours.`,
          size: 22,
          color: COLORS.text,
        }),
      ],
    })
  );

  // Weekly plan table
  if (curriculum.pacing.weeklyPlan && curriculum.pacing.weeklyPlan.length > 0) {
    const tableRows: TableRow[] = [
      // Header row
      new TableRow({
        children: [
          new TableCell({
            children: [
              new Paragraph({
                text: "Week",
                children: [
                  new TextRun({
                    text: "Week",
                    bold: true,
                    color: "FFFFFF",
                    size: 22,
                  }),
                ],
              }),
            ],
            shading: {
              type: ShadingType.CLEAR,
              color: COLORS.primary,
              fill: COLORS.primary,
            },
            verticalAlign: VerticalAlign.CENTER,
          }),
          new TableCell({
            children: [
              new Paragraph({
                text: "Focus",
                children: [
                  new TextRun({
                    text: "Focus",
                    bold: true,
                    color: "FFFFFF",
                    size: 22,
                  }),
                ],
              }),
            ],
            shading: {
              type: ShadingType.CLEAR,
              color: COLORS.primary,
              fill: COLORS.primary,
            },
            verticalAlign: VerticalAlign.CENTER,
          }),
        ],
        height: { value: 500, rule: "atLeast" },
      }),
    ];

    // Data rows
    curriculum.pacing.weeklyPlan.forEach((week, idx) => {
      const moduleLabels = week.moduleIds
        .map((id) => {
          const module = curriculum.modules.find((m) => m.id === id);
          return module ? module.title : id;
        })
        .join(", ");

      tableRows.push(
        new TableRow({
          children: [
            new TableCell({
              children: [
                new Paragraph({
                  text: `Week ${week.week}`,
                  children: [
                    new TextRun({
                      text: `Week ${week.week}`,
                      bold: true,
                      size: 22,
                    }),
                  ],
                }),
              ],
              shading: idx % 2 === 0 ? undefined : {
                type: ShadingType.CLEAR,
                color: COLORS.lightGray,
                fill: COLORS.lightGray,
              },
              verticalAlign: VerticalAlign.CENTER,
            }),
            new TableCell({
              children: [
                new Paragraph({
                  text: week.label ? `${week.label} (${moduleLabels})` : moduleLabels,
                  children: [
                    new TextRun({
                      text: week.label
                        ? `${week.label} (${moduleLabels})`
                        : moduleLabels,
                      size: 22,
                    }),
                  ],
                }),
              ],
              shading: idx % 2 === 0 ? undefined : {
                type: ShadingType.CLEAR,
                color: COLORS.lightGray,
                fill: COLORS.lightGray,
              },
              verticalAlign: VerticalAlign.CENTER,
            }),
          ],
          height: { value: 500, rule: "atLeast" },
        })
      );
    });

    paragraphs.push(
      new Table({
        width: { size: 100, type: "pct" },
        rows: tableRows,
        borders: {
          top: {
            color: COLORS.border,
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6,
          },
          bottom: {
            color: COLORS.border,
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6,
          },
          left: {
            color: COLORS.border,
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6,
          },
          right: {
            color: COLORS.border,
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6,
          },
          insideHorizontal: {
            color: COLORS.border,
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6,
          },
          insideVertical: {
            color: COLORS.border,
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6,
          },
        },
      })
    );
  }

  return paragraphs;
}

/**
 * Create the bonus resources section
 */
function createBonusResources(curriculum: Curriculum): Paragraph[] {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: "Bonus Resources",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: "Bonus Resources",
          size: 32,
          bold: true,
          color: COLORS.primary,
        }),
      ],
    }),
  ];

  if (!curriculum.bonusResources || curriculum.bonusResources.length === 0) {
    paragraphs.push(
      new Paragraph({
        text: "No bonus resources available for this curriculum.",
        children: [
          new TextRun({
            text: "No bonus resources available for this curriculum.",
            size: 22,
            italics: true,
            color: "6B7280",
          }),
        ],
      })
    );
    return paragraphs;
  }

  curriculum.bonusResources.forEach((resource) => {
    paragraphs.push(
      new Paragraph({
        text: `${resource.title}`,
        spacing: { before: 150, after: 80 },
        children: [
          new TextRun({
            text: resource.title,
            size: 22,
            bold: true,
            color: COLORS.primary,
          }),
        ],
      }),
      new Paragraph({
        text: `Type: ${resource.type} | ${resource.isFree ? "Free" : "Paid"}${resource.durationMinutes ? ` | ${resource.durationMinutes} min` : ""}`,
        spacing: { after: 80 },
        children: [
          new TextRun({
            text: `Type: `,
            bold: true,
            color: COLORS.light,
            size: 20,
          }),
          new TextRun({
            text: `${resource.type} | ${resource.isFree ? "Free" : "Paid"}${resource.durationMinutes ? ` | ${resource.durationMinutes} min` : ""}`,
            size: 20,
          }),
        ],
      })
    );

    if (resource.description) {
      paragraphs.push(
        new Paragraph({
          text: resource.description,
          spacing: { after: 80 },
          children: [
            new TextRun({
              text: resource.description,
              size: 20,
              color: COLORS.text,
            }),
          ],
        })
      );
    }

    paragraphs.push(
      new Paragraph({
        text: resource.url,
        spacing: { after: 150 },
        children: [
          new TextRun({
            text: resource.url,
            size: 20,
            color: "0066CC",
          }),
        ],
      })
    );
  });

  return paragraphs;
}

/**
 * Create the learning checklist section
 */
function createLearningChecklist(curriculum: Curriculum): Paragraph[] {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: "Learning Checklist",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: "Learning Checklist",
          size: 32,
          bold: true,
          color: COLORS.primary,
        }),
      ],
    }),
    new Paragraph({
      text: "Use this checklist to track your progress through the curriculum.",
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: "Use this checklist to track your progress through the curriculum.",
          size: 22,
          italics: true,
          color: COLORS.text,
        }),
      ],
    }),
  ];

  curriculum.modules.forEach((module, moduleIdx) => {
    paragraphs.push(
      new Paragraph({
        text: `Module ${moduleIdx + 1}: ${module.title}`,
        spacing: { before: 200, after: 150 },
        children: [
          new TextRun({
            text: `Module ${moduleIdx + 1}: ${module.title}`,
            size: 24,
            bold: true,
            color: COLORS.dark,
          }),
        ],
      })
    );

    module.lessons.forEach((lesson) => {
      paragraphs.push(
        new Paragraph({
          text: `☐ ${lesson.title}`,
          spacing: { after: 100 },
          children: [
            new TextRun({
              text: `☐ `,
              size: 22,
              color: COLORS.primary,
            }),
            new TextRun({
              text: lesson.title,
              size: 22,
              color: COLORS.text,
            }),
          ],
        })
      );
    });

    paragraphs.push(
      new Paragraph({
        text: "",
        spacing: { after: 150 },
      })
    );
  });

  return paragraphs;
}

/**
 * Format lesson format badge (e.g., "video" -> "VIDEO")
 */
function formatBadge(format: string): string {
  return format.toUpperCase().replace(/-/g, " ");
}
