import type { Curriculum } from "@/types/curriculum";

const MOD_PREFIX_RE = /^(?:module|chapter|session|unit|lesson|scene)\s*\d+\s*[:.\-–—]\s*/i;

export function generateNotebookLMMarkdown(c: Curriculum): string {
  const lines: string[] = [];

  lines.push(`# ${c.title}`);
  lines.push("");
  if (c.subtitle) {
    lines.push(c.subtitle);
    lines.push("");
  }
  lines.push(c.description);
  lines.push("");
  lines.push(`Target audience: ${c.targetAudience}. Difficulty: ${c.difficulty}. Total duration: ${c.pacing.totalHours} hours over ${c.pacing.totalWeeks} weeks at ${c.pacing.hoursPerWeek} hours per week.`);
  lines.push("");

  if (c.objectives.length > 0) {
    lines.push("## Learning objectives");
    lines.push("");
    c.objectives.forEach((o) => lines.push(`- ${o}`));
    lines.push("");
  }

  if (c.prerequisites && c.prerequisites.length > 0) {
    lines.push("## Prerequisites");
    lines.push("");
    c.prerequisites.forEach((p) => lines.push(`- ${p}`));
    lines.push("");
  }

  c.modules.forEach((mod) => {
    const modNum = (mod.order ?? 0) + 1;
    const cleanTitle = mod.title.replace(MOD_PREFIX_RE, "");
    lines.push(`## Module ${modNum}: ${cleanTitle}`);
    lines.push("");
    lines.push(mod.description);
    lines.push("");

    if (mod.objectives && mod.objectives.length > 0) {
      lines.push("Module objectives:");
      mod.objectives.forEach((o) => lines.push(`- ${o}`));
      lines.push("");
    }

    mod.lessons.forEach((l, idx) => {
      lines.push(`### Lesson ${modNum}.${idx + 1}: ${l.title}`);
      lines.push("");
      if (l.description) {
        lines.push(l.description);
        lines.push("");
      }

      if (l.content) {
        lines.push(l.content);
        lines.push("");
      }

      if (l.keyPoints && l.keyPoints.length > 0) {
        lines.push("Key points:");
        l.keyPoints.forEach((kp) => lines.push(`- ${kp}`));
        lines.push("");
      }

      if (l.suggestedResources && l.suggestedResources.length > 0) {
        lines.push("Resources:");
        l.suggestedResources.forEach((r) => {
          if (r.status === "unreachable" || r.status === "blocked") return;
          lines.push(`- ${r.title} (${r.url})`);
        });
        lines.push("");
      }

      if (l.resources && l.resources.length > 0) {
        lines.push("Further reading:");
        l.resources.forEach((r) => {
          if (r.status === "unreachable" || r.status === "blocked") return;
          lines.push(`- ${r.title} (${r.url})${r.description ? ` — ${r.description}` : ""}`);
        });
        lines.push("");
      }
    });
  });

  if (c.bonusResources && c.bonusResources.length > 0) {
    lines.push("## Bonus resources");
    lines.push("");
    c.bonusResources.forEach((r) => {
      if (r.status === "unreachable" || r.status === "blocked") return;
      lines.push(`- ${r.title} (${r.url})${r.description ? ` — ${r.description}` : ""}`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(`Generated by Syllabi (https://syllabi.online) — drop this file into Google NotebookLM to generate a conversational podcast of your course.`);

  return lines.join("\n");
}

export function notebookLMFilename(c: Curriculum, length?: string | null): string {
  const slug = c.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "course";
  const date = new Date().toISOString().slice(0, 10);
  const lengthSuffix = length ? `-${length}` : "";
  return `${slug}${lengthSuffix}-${date}.md`;
}
