import type { Curriculum, Lesson, Module } from "@/types/curriculum";

const MOD_PREFIX_RE = /^(?:module|chapter|session|unit|lesson|scene)\s*\d+\s*[:.\-–—]\s*/i;
const SLIDE_SEP = "\n\n---\n\n";
const MAX_BULLETS_PER_SLIDE = 5;
const MAX_SPEAKER_NOTES_CHARS = 900;

function escapeHtmlComment(text: string): string {
  return text.replace(/-->/g, "--&gt;");
}

function stripMarkdown(text: string): string {
  return text
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^>\s*/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > max * 0.7 ? cut.slice(0, lastSpace) : cut).trimEnd() + "…";
}

function speakerNotes(parts: (string | null | undefined)[]): string {
  const joined = parts
    .map((p) => (p ?? "").trim())
    .filter(Boolean)
    .join(" — ");
  if (!joined) return "";
  const clean = stripMarkdown(joined);
  const safe = escapeHtmlComment(truncate(clean, MAX_SPEAKER_NOTES_CHARS));
  return `<!-- Speaker notes: ${safe} -->`;
}

function cleanTitle(raw: string): string {
  return raw.replace(MOD_PREFIX_RE, "").trim();
}

function coverSlide(c: Curriculum): string {
  const lines: string[] = [];
  lines.push(`# ${c.title}`);
  if (c.subtitle) {
    lines.push("");
    lines.push(`## ${c.subtitle}`);
  }
  const stats = [
    `${c.modules?.length ?? 0} modules`,
    c.pacing?.totalHours ? `${c.pacing.totalHours}h total` : null,
    c.difficulty ? c.difficulty : null,
  ]
    .filter(Boolean)
    .join(" · ");
  if (stats) {
    lines.push("");
    lines.push(`_${stats}_`);
  }
  const notes = speakerNotes([c.description, c.targetAudience]);
  if (notes) {
    lines.push("");
    lines.push(notes);
  }
  return lines.join("\n");
}

function objectivesSlide(c: Curriculum): string | null {
  if (!c.objectives || c.objectives.length === 0) return null;
  const lines: string[] = [];
  lines.push(`# Learning Objectives`);
  lines.push("");
  c.objectives.slice(0, MAX_BULLETS_PER_SLIDE).forEach((o) => lines.push(`- ${o}`));
  const overflow = c.objectives.length - MAX_BULLETS_PER_SLIDE;
  if (overflow > 0) {
    lines.push("");
    lines.push(`_+${overflow} more objectives_`);
  }
  const notes = speakerNotes([c.objectives.join(" • ")]);
  if (notes) {
    lines.push("");
    lines.push(notes);
  }
  return lines.join("\n");
}

function moduleIntroSlide(mod: Module, index: number): string {
  const num = (mod.order ?? index) + 1;
  const title = cleanTitle(mod.title || `Module ${num}`);
  const lines: string[] = [];
  lines.push(`# Module ${num}: ${title}`);
  if (mod.description) {
    lines.push("");
    lines.push(mod.description);
  }
  if (mod.objectives && mod.objectives.length > 0) {
    lines.push("");
    mod.objectives.slice(0, MAX_BULLETS_PER_SLIDE).forEach((o) => lines.push(`- ${o}`));
  }
  const notes = speakerNotes([
    mod.description,
    mod.objectives?.length ? `Objectives: ${mod.objectives.join("; ")}` : null,
  ]);
  if (notes) {
    lines.push("");
    lines.push(notes);
  }
  return lines.join("\n");
}

function lessonSlide(lesson: Lesson, modIndex: number, lessonIndex: number): string {
  const num = `${modIndex + 1}.${lessonIndex + 1}`;
  const title = cleanTitle(lesson.title || `Lesson ${num}`);
  const lines: string[] = [];
  lines.push(`# ${num} · ${title}`);

  const bulletSource =
    lesson.keyPoints && lesson.keyPoints.length > 0
      ? lesson.keyPoints
      : lesson.objectives && lesson.objectives.length > 0
      ? lesson.objectives
      : lesson.description
      ? [lesson.description]
      : [];

  const bullets = bulletSource.slice(0, MAX_BULLETS_PER_SLIDE);
  if (bullets.length > 0) {
    lines.push("");
    bullets.forEach((b) => lines.push(`- ${b}`));
  }

  const meta: string[] = [];
  if (lesson.durationMinutes) meta.push(`${lesson.durationMinutes} min`);
  if (lesson.format) meta.push(lesson.format);
  if (meta.length > 0) {
    lines.push("");
    lines.push(`_${meta.join(" · ")}_`);
  }

  const notes = speakerNotes([
    lesson.content || lesson.description,
    lesson.keyPoints && lesson.keyPoints.length > MAX_BULLETS_PER_SLIDE
      ? `Additional key points: ${lesson.keyPoints.slice(MAX_BULLETS_PER_SLIDE).join("; ")}`
      : null,
  ]);
  if (notes) {
    lines.push("");
    lines.push(notes);
  }

  return lines.join("\n");
}

function closingSlide(c: Curriculum): string {
  const lines: string[] = [];
  lines.push(`# Thank you`);
  lines.push("");
  lines.push(`_${c.title}_`);
  lines.push("");
  lines.push(`Generated by [Syllabi](https://syllabi.online)`);
  const notes = speakerNotes([
    "Drop this markdown into Google NotebookLM and ask for a slide deck — or open it in Marp / Slidev for a ready-to-present deck.",
  ]);
  if (notes) {
    lines.push("");
    lines.push(notes);
  }
  return lines.join("\n");
}

export function generateNotebookLMSlidesMarkdown(c: Curriculum): string {
  const frontmatter = [
    "---",
    "marp: true",
    "theme: default",
    "paginate: true",
    `title: ${JSON.stringify(c.title)}`,
    "---",
  ].join("\n");

  const slides: string[] = [];
  slides.push(coverSlide(c));

  const objSlide = objectivesSlide(c);
  if (objSlide) slides.push(objSlide);

  c.modules?.forEach((mod, mi) => {
    slides.push(moduleIntroSlide(mod, mi));
    mod.lessons?.forEach((lesson, li) => {
      slides.push(lessonSlide(lesson, mi, li));
    });
  });

  slides.push(closingSlide(c));

  return `${frontmatter}\n\n${slides.join(SLIDE_SEP)}\n`;
}

export function notebookLMSlidesFilename(c: Curriculum): string {
  const slug =
    c.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "course";
  const date = new Date().toISOString().slice(0, 10);
  return `${slug}-slides-${date}.md`;
}
