/**
 * lib/exports/toMarkdown.ts
 * ---------------------------------------------------------
 * Converts a Curriculum object into a clean Markdown string.
 *
 * Used by the "Copy as Markdown" button in CurriculumOutput.
 * The resulting Markdown is suitable for pasting into Notion,
 * Google Docs, or any editor that supports Markdown formatting.
 *
 * @example
 *   import { curriculumToMarkdown } from '@/lib/exports/toMarkdown'
 *   const md = curriculumToMarkdown(curriculum)
 *   navigator.clipboard.writeText(md)
 * ---------------------------------------------------------
 */

import type { Curriculum } from "@/types/curriculum";

/**
 * Converts a Curriculum object to a complete Markdown document.
 *
 * Sections included:
 *   - Title, subtitle, description
 *   - Learning outcomes (objectives)
 *   - Modules with lessons (title, objectives, duration)
 *   - Quiz questions with answers and explanations
 *   - Pacing schedule with weekly breakdown
 *   - Bonus resources with type badges
 *
 * @param c - The Curriculum object to convert
 * @returns A formatted Markdown string
 */
export function curriculumToMarkdown(c: Curriculum): string {
  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────
  lines.push(`# ${c.title}`);
  lines.push(`**${c.subtitle}**\n`);
  lines.push(`${c.description}\n`);

  // ── Learning Outcomes ───────────────────────────────────
  lines.push(`## Learning Outcomes`);
  c.objectives.forEach((o) => lines.push(`- ${o}`));
  lines.push("");

  // ── Modules ─────────────────────────────────────────────
  c.modules.forEach((mod) => {
    // Module heading with order number
    lines.push(`## Module ${mod.order + 1}: ${mod.title}`);
    lines.push(`${mod.description}\n`);

    // Lessons within the module
    mod.lessons.forEach((l) => {
      lines.push(`### Lesson ${l.order + 1}: ${l.title}`);
      if (l.objectives && l.objectives.length > 0) {
        lines.push(`**Objectives:** ${l.objectives.join(", ")}`);
      }
      lines.push(`**Duration:** ${l.durationMinutes} mins`);
      lines.push("");
    });

    // Quiz section (if any questions exist)
    if (mod.quiz && mod.quiz.length > 0) {
      lines.push(`### Quiz`);
      mod.quiz.forEach((q, i) => {
        lines.push(`**Q${i + 1}: ${q.question}**`);
        // List all answer options
        if (q.options) {
          q.options.forEach((opt) => lines.push(`- ${opt}`));
        }
        // Resolve correct answer — could be an index (number) or string
        const answerText =
          typeof q.correctAnswer === "number" && q.options
            ? q.options[q.correctAnswer]
            : q.correctAnswer;
        lines.push(`✅ **Answer:** ${answerText}`);
        if (q.explanation) {
          lines.push(`💡 ${q.explanation}\n`);
        }
      });
    }
  });

  // ── Pacing Schedule ─────────────────────────────────────
  lines.push(`## Pacing Schedule`);
  if (c.pacing) {
    lines.push(`**Total Duration:** ${c.pacing.totalHours} hours\n`);
    if (c.pacing.weeklyPlan) {
      c.pacing.weeklyPlan.forEach((w) => {
        const moduleLabel =
          w.moduleIds?.length
            ? w.moduleIds.map(id => { const mod = c.modules.find(m => m.id === id); return mod ? mod.title.replace(/^Module\s*\d+\s*[:\.]\s*/i, "") : id; }).join(", ")
            : w.label || "TBD";
        lines.push(
          `- **Week ${w.week}:** ${moduleLabel} — ${c.pacing.hoursPerWeek}h/week`
        );
      });
    }
  }
  lines.push("");

  // ── Bonus Resources ─────────────────────────────────────
  if (c.bonusResources && c.bonusResources.length > 0) {
    lines.push(`## Bonus Resources`);
    c.bonusResources.forEach((r) =>
      lines.push(`- **${r.title}** *(${r.type})*: ${r.description}`)
    );
  }

  // ── Footer ──────────────────────────────────────────────
  lines.push("");
  lines.push("---");
  lines.push("*Generated by [Syllabi](https://syllabi.online)*");

  return lines.join("\n");
}
