"use client";

import { useEffect, useState, useCallback } from "react";
import { supabaseBrowser } from "@/lib/supabase";
import type { User } from "@supabase/supabase-js";
import type { Curriculum } from "@/types/curriculum";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  GraduationCap,
  BookOpen,
  Clock,
  Target,
  ArrowLeft,
  User as UserIcon,
  Sparkles,
  Download,
  FileText,
  Trash2,
  Sun,
  Moon,
  ExternalLink,
} from "lucide-react";
import { generateCurriculumPDF } from "@/lib/pdf/generatePDF";

interface Generation {
  id: string;
  topic: string;
  audience: string;
  length: string;
  niche: string | null;
  curriculum: Curriculum;
  created_at: string;
}

const difficultyColors: Record<string, string> = {
  beginner: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
  intermediate: "bg-amber-500/10 text-amber-400 border-amber-500/20",
  advanced: "bg-rose-500/10 text-rose-400 border-rose-500/20",
};

export default function ProfilePage() {
  const [dark, setDark] = useState(true);
  const [user, setUser] = useState<User | null>(null);
  const [generations, setGenerations] = useState<Generation[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
  }, [dark]);

  useEffect(() => {
    async function loadProfile() {
      const { data: { user } } = await supabaseBrowser.auth.getUser();
      setUser(user);

      if (user) {
        const { data, error } = await supabaseBrowser
          .from("generations")
          .select("*")
          .order("created_at", { ascending: false });

        if (data && !error) {
          setGenerations(data as Generation[]);
        }
      }
      setLoading(false);
    }
    loadProfile();
  }, []);

  const handleDownloadPDF = useCallback((curriculum: Curriculum) => {
    try {
      const pdf = generateCurriculumPDF(curriculum);
      pdf.save(`${curriculum.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_syllabus.pdf`);
    } catch (e) {
      console.error("Failed to generate PDF:", e);
    }
  }, []);

  const handleExportNotion = useCallback((curriculum: Curriculum) => {
    const lines: string[] = [];
    lines.push(`# ${curriculum.title}`);
    lines.push("");
    lines.push(`> ${curriculum.subtitle}`);
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## \u{1F4CB} Course Overview");
    lines.push("");
    lines.push("| Detail | Info |");
    lines.push("|---|---|");
    lines.push(`| **Difficulty** | ${curriculum.difficulty} |`);
    lines.push(`| **Target Audience** | ${curriculum.targetAudience} |`);
    lines.push(`| **Modules** | ${curriculum.modules.length} |`);
    const totalLessons = curriculum.modules.reduce((a, m) => a + (m.lessons?.length || 0), 0);
    lines.push(`| **Lessons** | ${totalLessons} |`);
    lines.push(`| **Duration** | ${curriculum.pacing?.totalHours || "N/A"} hours |`);
    lines.push("");
    lines.push(`${curriculum.description}`);
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## \u{1F3AF} Learning Objectives");
    lines.push("");
    curriculum.objectives.forEach((obj) => lines.push(`- [ ] ${obj}`));
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## \u{1F4DA} Curriculum");
    lines.push("");
    curriculum.modules.forEach((mod) => {
      lines.push(`### Module ${(mod.order ?? 0) + 1}: ${mod.title}`);
      lines.push("");
      lines.push(`> ${mod.description}`);
      lines.push("");
      mod.lessons?.forEach((l, idx) => {
        lines.push(`#### ${idx + 1}. ${l.title} *(${l.durationMinutes} min)*`);
        if (l.keyPoints?.length) {
          l.keyPoints.forEach((kp) => lines.push(`- ${kp}`));
        }
        lines.push("");
      });
      if (mod.quiz?.length) {
        lines.push(`#### Quiz`);
        mod.quiz.forEach((q, i) => {
          lines.push(`**Q${i + 1}:** ${q.question}`);
          q.options?.forEach((opt) => lines.push(`- ${opt}`));
          lines.push("");
        });
      }
      lines.push("---");
      lines.push("");
    });
    lines.push(`> *Generated by [Syllabi.ai](https://syllabi.ai)*`);

    const md = lines.join("\n");
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${curriculum.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_notion.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, []);

  // Not signed in
  if (!loading && !user) {
    return (
      <div className="min-h-screen bg-background text-foreground flex items-center justify-center p-4">
        <Card className="max-w-md w-full text-center">
          <CardContent className="pt-8 pb-8">
            <div className="flex items-center justify-center size-16 rounded-2xl bg-violet-500/10 mx-auto mb-5">
              <UserIcon className="size-8 text-violet-500" />
            </div>
            <h1 className="text-xl font-bold mb-2">Sign in to view your profile</h1>
            <p className="text-sm text-muted-foreground mb-6">
              Sign in with Google to see your generated courses and export them anytime.
            </p>
            <div className="flex gap-3 justify-center">
              <Button variant="outline" onClick={() => window.location.href = "/"}>
                <ArrowLeft className="size-4 mr-2" />
                Back to Home
              </Button>
              <Button
                className="bg-gradient-to-r from-violet-600 to-indigo-600 text-white border-0"
                onClick={async () => {
                  await supabaseBrowser.auth.signInWithOAuth({
                    provider: "google",
                    options: { redirectTo: `${window.location.origin}/auth/callback?next=/profile` },
                  });
                }}
              >
                Sign in with Google
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  const avatarUrl = user?.user_metadata?.avatar_url;
  const name = user?.user_metadata?.full_name || user?.email?.split("@")[0] || "User";

  return (
    <div className="min-h-screen bg-background text-foreground transition-colors duration-300">
      {/* Nav */}
      <nav className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/60 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-4 sm:px-6">
          <a href="/" className="flex items-center gap-2 text-lg font-bold tracking-tight">
            <GraduationCap className="size-5 text-violet-500" />
            <span>syllabi<span className="text-violet-500">.ai</span></span>
          </a>
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="icon"
              className="rounded-full"
              onClick={() => setDark(!dark)}
            >
              {dark ? <Sun className="size-4" /> : <Moon className="size-4" />}
            </Button>
            <a href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Back to Generator
            </a>
          </div>
        </div>
      </nav>

      <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6">
        {/* Profile header */}
        <div className="flex items-center gap-4 mb-10">
          {avatarUrl ? (
            <img src={avatarUrl} alt={name} className="size-16 rounded-2xl ring-2 ring-violet-500/30 shadow-lg" />
          ) : (
            <div className="flex items-center justify-center size-16 rounded-2xl bg-violet-500/15 text-violet-500 ring-2 ring-violet-500/30">
              <UserIcon className="size-8" />
            </div>
          )}
          <div>
            <h1 className="text-2xl font-bold">{name}</h1>
            <p className="text-sm text-muted-foreground">{user?.email}</p>
            <div className="flex items-center gap-3 mt-1.5">
              <Badge variant="outline" className="text-xs border-violet-500/30 text-violet-500">
                {generations.length} course{generations.length !== 1 ? "s" : ""} generated
              </Badge>
            </div>
          </div>
        </div>

        {/* Courses */}
        <div className="mb-6 flex items-center justify-between">
          <h2 className="text-lg font-semibold flex items-center gap-2">
            <BookOpen className="size-5 text-violet-500" />
            My Courses
          </h2>
        </div>

        {loading ? (
          <div className="grid gap-4 sm:grid-cols-2">
            {[1, 2, 3, 4].map((i) => (
              <Card key={i} className="animate-pulse">
                <CardHeader className="pb-3">
                  <div className="h-5 bg-muted rounded w-3/4 mb-2" />
                  <div className="h-3 bg-muted rounded w-1/2" />
                </CardHeader>
                <CardContent>
                  <div className="h-3 bg-muted rounded w-full mb-2" />
                  <div className="h-3 bg-muted rounded w-2/3" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : generations.length === 0 ? (
          <Card className="text-center py-16">
            <CardContent>
              <Sparkles className="size-10 text-violet-500/40 mx-auto mb-4" />
              <h3 className="text-lg font-semibold mb-2">No courses yet</h3>
              <p className="text-sm text-muted-foreground mb-6 max-w-md mx-auto">
                Generate your first AI-powered course and it will appear here. You can export, revisit, and download anytime.
              </p>
              <Button
                className="bg-gradient-to-r from-violet-600 to-indigo-600 text-white border-0"
                onClick={() => window.location.href = "/"}
              >
                Generate Your First Course
              </Button>
            </CardContent>
          </Card>
        ) : (
          <div className="grid gap-4 sm:grid-cols-2">
            {generations.map((gen) => {
              const c = gen.curriculum;
              const totalLessons = c.modules?.reduce((a, m) => a + (m.lessons?.length || 0), 0) || 0;
              const isExpanded = expandedId === gen.id;

              return (
                <Card
                  key={gen.id}
                  className="group border-border/50 bg-card/50 backdrop-blur-sm hover:border-violet-500/30 transition-all duration-200 cursor-pointer"
                  onClick={() => setExpandedId(isExpanded ? null : gen.id)}
                >
                  <CardHeader className="pb-3">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0">
                        <h3 className="font-semibold text-sm leading-snug truncate">{c.title}</h3>
                        <p className="text-xs text-muted-foreground mt-0.5 truncate">{c.subtitle}</p>
                      </div>
                      <Badge
                        variant="outline"
                        className={`text-[10px] shrink-0 ${difficultyColors[c.difficulty] || ""}`}
                      >
                        {c.difficulty}
                      </Badge>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="flex flex-wrap gap-2 mb-3">
                      <div className="flex items-center gap-1 text-xs text-muted-foreground">
                        <BookOpen className="size-3" />
                        {c.modules?.length || 0} modules
                      </div>
                      <div className="flex items-center gap-1 text-xs text-muted-foreground">
                        <Target className="size-3" />
                        {totalLessons} lessons
                      </div>
                      <div className="flex items-center gap-1 text-xs text-muted-foreground">
                        <Clock className="size-3" />
                        {c.pacing?.totalHours || 0}h
                      </div>
                    </div>
                    <p className="text-xs text-muted-foreground line-clamp-2 mb-3">{c.description}</p>
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] text-muted-foreground/60">
                        {new Date(gen.created_at).toLocaleDateString("en-US", {
                          month: "short",
                          day: "numeric",
                          year: "numeric",
                        })}
                      </span>
                      <div className="flex gap-1.5">
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-[10px] hover:bg-violet-500/10 hover:text-violet-500"
                          onClick={(e) => { e.stopPropagation(); handleDownloadPDF(c); }}
                        >
                          <Download className="size-3 mr-1" />
                          PDF
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-[10px] hover:bg-purple-500/10 hover:text-purple-500"
                          onClick={(e) => { e.stopPropagation(); handleExportNotion(c); }}
                        >
                          <FileText className="size-3 mr-1" />
                          Notion
                        </Button>
                      </div>
                    </div>

                    {/* Expanded details */}
                    {isExpanded && (
                      <div className="mt-4 pt-4 border-t border-border/30 space-y-3">
                        <div>
                          <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1.5">
                            Learning Objectives
                          </p>
                          <ul className="space-y-1">
                            {c.objectives?.slice(0, 5).map((obj, i) => (
                              <li key={i} className="text-xs text-muted-foreground flex items-start gap-1.5">
                                <span className="text-violet-500 mt-0.5 shrink-0">\u2022</span>
                                {obj}
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div>
                          <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1.5">
                            Modules
                          </p>
                          <ul className="space-y-1">
                            {c.modules?.map((mod, i) => (
                              <li key={i} className="text-xs text-muted-foreground">
                                <span className="text-foreground font-medium">{i + 1}.</span> {mod.title}
                                <span className="text-muted-foreground/50 ml-1">
                                  ({mod.lessons?.length || 0} lessons)
                                </span>
                              </li>
                            ))}
                          </ul>
                        </div>
                        {c.tags && c.tags.length > 0 && (
                          <div className="flex flex-wrap gap-1.5 pt-1">
                            {c.tags.map((tag, i) => (
                              <Badge key={i} variant="secondary" className="text-[10px]">
                                {tag}
                              </Badge>
                            ))}
                          </div>
                        )}
                      </div>
                    )}
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}
