-- Migration 014: CHECK constraint on courses.length + drift cleanup
-- ─────────────────────────────────────────────────────────────
-- Production contains stray length values (mini, beginner,
-- intermediate) that the application code does not handle.
-- These are dev-test artifacts from earlier schema versions
-- generated by Gianmarco + Filippo.
--
-- This migration:
--   1. Maps any stray value to 'crash' (safest fallback)
--   2. Adds a CHECK constraint restricting future inserts/updates
--      to the four valid values the code handles.
--
-- Mapping to 'crash' rather than deleting rows preserves the
-- historical failure data for investigation.
-- ─────────────────────────────────────────────────────────────

DO $$
DECLARE
  stray_count integer;
BEGIN
  SELECT count(*) INTO stray_count
  FROM public.courses
  WHERE length NOT IN ('crash', 'short', 'full', 'masterclass');

  IF stray_count > 0 THEN
    RAISE NOTICE 'Migration 014: mapping % rows with stray length values to ''crash''', stray_count;
    UPDATE public.courses
    SET length = 'crash'
    WHERE length NOT IN ('crash', 'short', 'full', 'masterclass');
  END IF;
END $$;

ALTER TABLE public.courses
  ADD CONSTRAINT courses_length_valid
  CHECK (length IN ('crash', 'short', 'full', 'masterclass'));

COMMENT ON CONSTRAINT courses_length_valid ON public.courses IS
  'Added in migration 014 after observing schema drift in production. Restricts courses.length to the four values the application code handles.';
